vim.cmd([[ let g:airline#extensions#tabline#enabled = 0 ]])
vim.cmd([[ let g:airline#extensions#tabline#left_sep = ' ' ]])
vim.cmd([[ let g:airline#extensions#tabline#left_alt_sep = '|' ]])
vim.cmd([[ let g:airline#extensions#tabline#formatter = 'unique_tail' ]])
vim.cmd([[ let g:airline_theme='jellybeans' ]])
